
singleton TSShapeConstructor(basemale1_4Dts)
{
   baseShape = "./BaseMale1_4.dts";
};

function basemale1_4Dts::onLoad(%this)
{
   %this.renameNode("upperJaw", "Eye");
   %this.setNodeTransform("eye", "0.000158001 0.126053 2.43575 1 0 0 0", "1");
   %this.setNodeTransform("mount3", "-0.214266 0.17907 1.61817 1 0 0 0", "1");
   %this.addNode("cam", "root", "0 -0.54884 2.24219 1 0 0 0", "1");
   %this.addNode("mount7", "mount0", "1.15735 0.129206 2.07096 0.705299 -0.682394 -0.192072 3.04478", "1");
   %this.addNode("mount2", "lHand", "-1.09296 0.158002 2.04113 1 0 0 0", "1");
   %this.addNode("mount10", "rToe", "0.174183 0.0105287 0.041622 1 0 0 0", "1");
   %this.addNode("mount12", "lToe", "-0.210012 -0.00454873 0.0478135 1 0 0 0", "1");
   %this.addNode("mount1", "lHand", "-1.15746 0.192278 2.00405 -0.300286 0.910571 -0.284058 0.485323", "1");
   %this.addNode("mount31", "root", "0 0 0.00427338 1 0 0 0", "1");
   %this.addSequence("art/players/base/Anims/Root_Sword.dsq", "Root", "0", "383", "1", "0");
   %this.setSequenceCyclic("Root", "1");
   %this.addSequence("art/players/base/Anims/Head.dsq", "Head", "0", "2", "1", "0");
   %this.setSequenceBlend("head", "1", "Root", "0");
   %this.addSequence("art/players/base/Anims/HeadSide.dsq", "HeadSide", "0", "2", "1", "0");
   %this.setSequenceBlend("HeadSide", "1", "Root", "0");
   %this.addSequence("art/players/base/Anims/CombatRun.dsq", "Run", "0", "29", "1", "0");
   %this.setSequenceCyclic("Run", "1");
   %this.addSequence("art/players/base/Anims/Back.dsq", "Back", "0", "29", "1", "0");
   %this.addTrigger("Back", "3", "1");
   %this.addTrigger("Back", "16", "2");
   %this.addSequence("art/players/base/Anims/Left.dsq", "Left", "0", "29", "1", "0");
   %this.addTrigger("Left", "3", "1");
   %this.addTrigger("Left", "18", "2");
   %this.addSequence("art/players/base/Anims/Right.dsq", "Right", "0", "29", "1", "0");
   %this.addTrigger("right", "2", "2");
   %this.addTrigger("right", "17", "1");
   %this.addSequence("art/players/base/Anims/Root_Sword.dsq", "RunFull_Root", "0", "383", "1", "0");
   %this.setSequencePriority("RunFull_Root", "0");
   %this.addSequence("art/players/base/Anims/RunFull_Left.dsq", "RunFull_Left", "0", "29", "1", "0");
   %this.addTrigger("RunFull_Left", "3", "1");
   %this.addTrigger("RunFull_Left", "19", "2");
   %this.addSequence("art/players/base/Anims/RunFull_Right.dsq", "RunFull_Right", "0", "29", "1", "0");
   %this.addTrigger("RunFull_Right", "3", "1");
   %this.addTrigger("RunFull_Right", "18", "2");
   %this.addSequence("art/players/base/Anims/GA_Back.dsq", "RunFull_Back", "0", "29", "1", "0");
   %this.setSequenceCyclic("RunFull_Back", "1");
   %this.addSequence("art/players/base/Anims/CombatRun.dsq", "RunFull_Forward", "0", "29", "1", "0");
   %this.setSequenceCyclic("RunFull_Forward", "1");
   %this.addSequence("art/players/base/Anims/Sprint_Forward.dsq", "Sprint_Forward", "0", "78", "1", "0");
   %this.addTrigger("Sprint_Forward", "4", "1");
   %this.addTrigger("Sprint_Forward", "22", "2");
   %this.addTrigger("Sprint_Forward", "42", "1");
   %this.addTrigger("Sprint_Forward", "62", "2");
   %this.addSequence("art/players/base/Anims/Root_Sword.dsq", "Sprint_Root", "0", "383", "1", "0");
   %this.setSequencePriority("Sprint_Root", "0");
   %this.addSequence("art/players/base/Anims/Sprint_Back.dsq", "Sprint_Back", "0", "29", "1", "0");
   %this.addTrigger("Sprint_Back", "4", "1");
   %this.addTrigger("Sprint_Back", "11", "2");
   %this.addSequence("art/players/base/Anims/Sprint_Left.dsq", "Sprint_Left", "0", "29", "1", "0");
   %this.addTrigger("Sprint_Left", "1", "1");
   %this.addTrigger("Sprint_Left", "8", "2");
   %this.addSequence("art/players/base/Anims/Sprint_Right.dsq", "Sprint_Right", "0", "29", "1", "0");
   %this.addTrigger("Sprint_Right", "1", "1");
   %this.addTrigger("Sprint_Right", "8", "2");
   %this.addSequence("art/players/base/Anims/Root_Sword.dsq", "SprintFull_Root", "0", "29", "1", "0");
   %this.setSequencePriority("SprintFull_Root", "0");
   %this.setSequenceCyclic("SprintFull_Root", "1");
   %this.addSequence("art/players/base/Anims/CombatSprint.dsq", "SprintFull_Forward", "0", "118", "1", "0");
   %this.setSequenceCyclic("SprintFull_Forward", "1");
   %this.addSequence("art/players/base/Anims/SprintFull_Back.dsq", "SprintFull_Back", "0", "29", "1", "0");
   %this.addTrigger("SprintFull_Back", "3", "1");
   %this.addTrigger("SprintFull_Back", "11", "2");
   %this.addTrigger("SprintFull_Back", "19", "1");
   %this.addTrigger("SprintFull_Back", "26", "2");
   %this.addSequence("art/players/base/Anims/SprintFull_Left.dsq", "SprintFull_Left", "0", "29", "1", "0");
   %this.addTrigger("SprintFull_Left", "0", "1");
   %this.addTrigger("SprintFull_Left", "8", "2");
   %this.addTrigger("SprintFull_Left", "15", "1");
   %this.addTrigger("SprintFull_Left", "23", "2");
   %this.addSequence("art/players/base/Anims/SprintFull_Right.dsq", "SprintFull_Right", "0", "29", "1", "0");
   %this.addTrigger("SprintFull_Right", "9", "2");
   %this.addTrigger("SprintFull_Right", "1", "1");
   %this.addTrigger("SprintFull_Right", "16", "1");
   %this.addTrigger("SprintFull_Right", "23", "2");
   %this.addSequence("art/players/base/Anims/StrafeRunLeft.dsq", "StrafeSprintLeft", "0", "25", "1", "0");
   %this.setSequenceCyclic("StrafeSprintLeft", "1");
   %this.addSequence("art/players/base/Anims/StrafeRunRight.dsq", "StrafeSprintRight", "0", "24", "1", "0");
   %this.setSequenceCyclic("StrafeSprintRight", "1");
   %this.addSequence("art/players/base/Anims/Crouch_Forward.dsq", "Crouch_Forward", "0", "41", "1", "0");
   %this.setSequenceCyclic("Crouch_Forward", "1");
   %this.addTrigger("Crouch_Forward", "6", "1");
   %this.addTrigger("Crouch_Forward", "25", "2");
   %this.addSequence("art/players/base/Anims/Crouch_Back.dsq", "Crouch_Back", "0", "41", "1", "0");
   %this.setSequenceCyclic("Crouch_Back", "1");
   %this.addTrigger("Crouch_Back", "28", "1");
   %this.addTrigger("Crouch_Back", "1", "2");
   %this.addSequence("art/players/base/Anims/Crouch_Left.dsq", "Crouch_Left", "0", "92", "1", "0");
   %this.setSequenceCyclic("Crouch_Left", "1");
   %this.addTrigger("Crouch_Left", "1", "1");
   %this.addTrigger("Crouch_Left", "21", "2");
   %this.addTrigger("Crouch_Left", "45", "1");
   %this.addTrigger("Crouch_Left", "69", "2");
   %this.addSequence("art/players/base/Anims/Crouch_Right.dsq", "Crouch_Right", "0", "92", "1", "0");
   %this.setSequenceCyclic("Crouch_Right", "1");
   %this.addTrigger("Crouch_Right", "1", "2");
   %this.addTrigger("Crouch_Right", "23", "1");
   %this.addTrigger("Crouch_Right", "47", "2");
   %this.addTrigger("Crouch_Right", "69", "1");
   %this.addSequence("art/players/base/Anims/CrouchFull_Root.dsq", "CrouchFull_Root", "0", "29", "1", "0");
   %this.addSequence("art/players/base/Anims/CrouchFull_Forward.dsq", "CrouchFull_Forward", "0", "55", "1", "0");
   %this.setSequenceCyclic("CrouchFull_Forward", "1");
   %this.addTrigger("CrouchFull_Forward", "10", "1");
   %this.addTrigger("CrouchFull_Forward", "33", "2");
   %this.addSequence("art/players/base/Anims/CrouchFull_Back.dsq", "CrouchFull_Back", "0", "55", "1", "0");
   %this.setSequenceCyclic("CrouchFull_Back", "1");
   %this.addTrigger("CrouchFull_Back", "38", "1");
   %this.addTrigger("CrouchFull_Back", "4", "2");
   %this.addSequence("art/players/base/Anims/CrouchFull_Left.dsq", "CrouchFull_Left", "0", "138", "1", "0");
   %this.setSequenceCyclic("CrouchFull_Left", "1");
   %this.addTrigger("CrouchFull_Left", "0", "1");
   %this.addTrigger("CrouchFull_Left", "70", "1");
   %this.addTrigger("CrouchFull_Left", "35", "2");
   %this.addTrigger("CrouchFull_Left", "105", "2");
   %this.addSequence("art/players/base/Anims/CrouchFull_Right.dsq", "CrouchFull_Right", "0", "138", "1", "0");
   %this.setSequenceCyclic("CrouchFull_Right", "1");
   %this.addTrigger("CrouchFull_Right", "2", "2");
   %this.addTrigger("CrouchFull_Right", "34", "1");
   %this.addTrigger("CrouchFull_Right", "68", "2");
   %this.addTrigger("CrouchFull_Right", "101", "1");
   %this.addSequence("art/players/base/Anims/Swim_Root.dsq", "SwimFull_Root", "0", "29", "1", "0");
   %this.addSequence("art/players/base/Anims/Swim_Backward.dsq", "SwimFull_Backward", "0", "29", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Swimming.dsq", "SwimFull_Forward", "0", "29", "1", "0");
   %this.setSequenceCyclic("SwimFull_Forward", "1");
   %this.addSequence("art/players/base/Anims/SwimFull_Forward.dsq", "SwimFull_Under", "0", "29", "1", "0");
   %this.addSequence("art/players/base/Anims/Fall.dsq", "Fall", "0", "29", "1", "0");
   %this.addSequence("art/players/base/Anims/Jump.dsq", "Jump", "0", "70", "1", "0");
   %this.addTrigger("jump", "40", "1");
   %this.addTrigger("jump", "40", "2");
   %this.addSequence("art/players/base/Anims/StandJump.dsq", "StandJump", "0", "70", "1", "0");
   %this.addTrigger("StandJump", "40", "1");
   %this.addTrigger("StandJump", "40", "2");
   %this.addSequence("art/players/base/Anims/FallFull.dsq", "FallFull", "0", "46", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_JumpRunning.dsq", "JumpRunning", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Land.dsq", "Land", "0", "29", "1", "0");
   %this.addTrigger("Land", "1", "1");
   %this.addTrigger("Land", "1", "2");
   %this.addSequence("art/players/base/Anims/Flip.dsq", "Flip", "0", "15", "1", "0");
   %this.addSequence("art/players/base/Anims/JumpFull.dsq", "JumpFull", "0", "60", "1", "0");
   %this.addTrigger("jumpfull", "40", "1");
   %this.addTrigger("jumpfull", "40", "2");
   %this.addSequence("art/players/base/Anims/Backflip.dsq", "BackFlipNew", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/JumpLeft.dsq", "JumpLeft", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/JumpRight.dsq", "JumpRight", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/LandFull.dsq", "LandFull", "0", "15", "1", "0");
   %this.addSequence("art/players/base/Anims/FlipFull.dsq", "FlipFull", "0", "15", "1", "0");
   %this.addSequence("art/players/base/Anims/TapLink.dsq", "TapLink", "0", "3", "1", "0");
   %this.setSequencePriority("TapLink", "5");
   %this.addSequence("art/players/base/Anims/ScoutRoot.dsq", "ScoutRoot", "0", "-1", "1", "0");
   %this.setSequenceCyclic("ScoutRoot", "1");
   %this.addSequence("art/players/base/Anims/GargSitFull.dsq", "GargSitFull", "0", "-1", "1", "0");
   %this.setSequenceCyclic("GargSitFull", "1");
   %this.addSequence("art/players/base/Anims/damageBody1.dsq", "DamageBody1", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/damageHead1.dsq", "DamageHead1", "0", "13", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_DamageHead1.dsq", "DamageHead2", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_DamageHeadLeft.dsq", "DamageBody_L1", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_DamageHeadRight.dsq", "DamageBody_R1", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/DamageLegs_L.dsq", "DamageLegs_L1", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/DamageLegs_R.dsq", "DamageLegs_R1", "0", "16", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_DamageFromBack.dsq", "DamageBody2", "0", "39", "1", "0");
   %this.addSequence("art/players/base/Anims/DamageKnockedBackward.dsq", "DamageBody3", "0", "120", "1", "0");
   %this.addSequence("art/players/base/Anims/DamageKnockedForward.dsq", "DamageBody4", "0", "99", "1", "0");
   %this.addSequence("art/players/base/Anims/Death1.dsq", "Death1", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death2.dsq", "Death2", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death3.dsq", "Death3", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death4.dsq", "Death4", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death5.dsq", "Death5", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death6.dsq", "Death6", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death7.dsq", "Death7", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death8.dsq", "Death8", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death9.dsq", "Death9", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death10.dsq", "Death10", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Death11.dsq", "Death11", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_DeathA.dsq", "Death12", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_DeathB.dsq", "Death13", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/DieFallForward.dsq", "Death14", "0", "24", "1", "0");
   %this.addSequence("art/players/base/Anims/Dieknockedbackward.dsq", "Death15", "0", "24", "1", "0");
   %this.addSequence("art/players/base/Anims/DieknockedForward.dsq", "Death16", "0", "16", "1", "0");
   %this.addSequence("art/players/base/Anims/DieFallBackward.dsq", "Death17", "0", "24", "1", "0");
   %this.addSequence("art/players/base/Anims/M_Root.dsq", "M_Root", "0", "74", "1", "0");
   %this.setSequenceCyclic("M_Root", "1");
   %this.addSequence("art/players/base/Anims/M_BuffSpellA.dsq", "M_BuffSpellA", "0", "74", "1", "0");
   %this.addSequence("art/players/base/Anims/M_BuffSpellB.dsq", "M_BuffSpellB", "0", "89", "1", "0");
   %this.addSequence("art/players/base/Anims/M_CombatModeA.dsq", "M_CombatMode", "0", "89", "1", "0");
   %this.setSequenceCyclic("M_CombatMode", "1");
   %this.addSequence("art/players/base/Anims/M_Damage1.dsq", "M_Damage1", "0", "74", "1", "0");
   %this.addSequence("art/players/base/Anims/M_DodgeLeft.dsq", "M_DodgeLeft", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_DodgeRight.dsq", "M_DodgeRight", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_DrinkingPotion.dsq", "M_DrinkPotion", "0", "54", "1", "0");
   %this.addSequence("art/players/base/Anims/M_DuckBelowSwing.dsq", "M_DuckSwing", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_FireballSpell.dsq", "M_FireballSpell", "0", "74", "1", "0");
   %this.addSequence("art/players/base/Anims/M_MagicHelix.dsq", "M_MagicHelix", "0", "69", "1", "0");
   %this.addSequence("art/players/base/Anims/M_MagicLight.dsq", "M_MagicLight", "0", "49", "1", "0");
   %this.addSequence("art/players/base/Anims/M_MagicShotStraight.dsq", "M_ShotStraight", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_MakingPotion.dsq", "M_MakePotion", "0", "29", "1", "0");
   %this.setSequenceCyclic("M_MakePotion", "1");
   %this.addSequence("art/players/base/Anims/M_Run.dsq", "M_Run", "0", "25", "1", "0");
   %this.setSequenceCyclic("M_Run", "1");
   %this.addSequence("art/players/base/Anims/M_RunHitA.dsq", "M_RunHitA", "0", "43", "1", "0");
   %this.addSequence("art/players/base/Anims/M_RunHitB.dsq", "M_RunHitB", "0", "43", "1", "0");
   %this.addSequence("art/players/base/Anims/M_RunHitC.dsq", "M_RunHitC", "0", "43", "1", "0");
   %this.addSequence("art/players/base/Anims/M_SpellCastA.dsq", "M_SpellCastA", "0", "69", "1", "0");
   %this.addSequence("art/players/base/Anims/M_SpellCastB.dsq", "M_SpellCastB", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_SpellCastC.dsq", "M_SpellCastC", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_SpellCastD.dsq", "M_SpellCastD", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_StaffBlock.dsq", "M_StaffBlock", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_StaffEarthQuake.dsq", "M_StaffEarthQuake", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_StaffHit.dsq", "M_StaffHit", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_StraightDownHit.dsq", "M_StaffHitStraightDown", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/M_SwingRight.dsq", "M_StaffSwingRight", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/CastSpell1.dsq", "M_CastSpell1", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/CastSpell2.dsq", "M_CastSpell2", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Summon.dsq", "M_Summon", "0", "29", "1", "0");
   %this.addSequence("art/players/base/Anims/fb.dsq", "M_fb", "0", "14", "1", "0");
   %this.addSequence("art/players/base/Anims/throw.dsq", "M_Throw", "0", "9", "1", "0");
   %this.addSequence("art/players/base/Anims/mlf.dsq", "M_Spin", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_ThrowGrenade.dsq", "Throw_Grenade", "0", "225", "1", "0");
   %this.setSequencePriority("Throw_Grenade", "5");
   %this.addSequence("art/players/base/Anims/Throw_HamAxe.dsq", "Throw_HamAxe", "0", "29", "1", "0");
   %this.addTrigger("Throw_HamAxe", "10", "3");
   %this.addSequence("art/players/base/Anims/Throw_Javelin.dsq", "Throw_Javelin", "1", "29", "1", "0");
   %this.addTrigger("Throw_Javelin", "9", "3");
   %this.addSequence("art/players/base/Anims/Cast.dsq", "CastLine", "0", "-1", "1", "0");
   %this.addTrigger("CastLine", "19", "3");
   %this.addSequence("art/players/base/Anims/xr75.dsq", "XR75", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Look_XR75.dsq", "Look_XR75", "2", "28", "1", "0");
   %this.addSequence("art/players/base/Anims/Fire_Flintlock_Full.dsq", "Fire_Flintlock", "0", "23", "1", "0");
   %this.addTrigger("Fire_Flintlock", "11", "3");
   %this.addSequence("art/players/base/Anims/LH_PunchCombo.dsq", "LH_PunchCombo", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/LH_PunchDown.dsq", "LH_PunchDown", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/LH_PunchJab.dsq", "LH_PunchJab", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/LH_PunchRound.dsq", "LH_PunchRound", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/RH_PunchCombo.dsq", "RH_PunchCombo", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/RH_PunchDown.dsq", "RH_PunchDown", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/RH_PunchJab.dsq", "RH_PunchJab", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/RH_PunchRound.dsq", "RH_PunchRound", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_PunchRH.dsq", "RH_PunchStraight", "0", "64", "1", "0");
   %this.addSequence("art/players/base/Anims/LF_KickLow.dsq", "LF_KickLow", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/LF_KickHigh.dsq", "LF_KickHigh", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/LF_SpinKick1.dsq", "LF_SpinKick1", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/RF_KickLow.dsq", "RF_KickLow", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/RF_KickHigh.dsq", "RF_KickHigh", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/RF_SpinKick1.dsq", "RF_SpinKick1", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Staff_Center.dsq", "Staff_Center", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/Staff_LHHigh.dsq", "Staff_LHHigh", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Staff_LHLow.dsq", "Staff_LHLow", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Staff_RHHigh.dsq", "Staff_RHHigh", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Staff_RHLow.dsq", "Staff_RHLow", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Staff_Spin.dsq", "Staff_Spin", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Staff_Lunge.dsq", "Staff_Lunge", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Block1_LH.dsq", "Block_LH1", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Block2_LH.dsq", "Block_LH2", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Block3_LH.dsq", "Block_LH3", "0", "29", "1", "0");
   %this.addSequence("art/players/base/Anims/Block4_LH.dsq", "Block_LH4", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Block1_RH.dsq", "Block_RH1", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Block2_RH.dsq", "Block_RH2", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Block3_RH.dsq", "Block_RH3", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Block4_RH.dsq", "Block_RH4", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing1.dsq", "SwordSwing1", "0", "44", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing2.dsq", "SwordSwing2", "0", "59", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing3.dsq", "SwordSwing3", "0", "69", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing4.dsq", "SwordSwing4", "0", "39", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing5.dsq", "SwordSwing5", "0", "44", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing6.dsq", "SwordSwing6", "0", "49", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing7.dsq", "SwordSwing7", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing8.dsq", "SwordSwing8", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing9.dsq", "SwordSwing9", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing10.dsq", "SwordSwing10", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing11.dsq", "SwordSwing11", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing12.dsq", "SwordSwing12", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing13.dsq", "SwordSwing13", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/SwordSwing14.dsq", "SwordSwing14", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/Wave.dsq", "celwave", "0", "18", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Shrugs.dsq", "celsalute", "0", "20", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/EdGrimly.dsq", "Emote_EdGrimly", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/BreakDance.dsq", "Emote_BreakDance", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/FolkDance.dsq", "Emote_FolkDance", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/HipHop.dsq", "Emote_HipHop", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/Ballet.dsq", "Emote_Ballet", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/BellyDancer.dsq", "Emote_BellyDancer", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/ClubDance1.dsq", "Emote_ClubDance1", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/ClubDance2.dsq", "Emote_ClubDance2", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/IrishJig.dsq", "Emote_IrishJig", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/LordDance.dsq", "Emote_LordDance", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/Macerana.dsq", "Emote_Macarena", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/NiteClubLoop1.dsq", "Emote_NightClubLoop1", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/NiteClubLoop2.dsq", "Emote_NightClubLoop2", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/PulpFiction.dsq", "Emote_PulpFiction", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/RiverDance.dsq", "Emote_RiverDance", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/SaturdayNight.dsq", "Emote_SaturdayNight", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/SnakeDance.dsq", "Emote_SnakeDance", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/SuperDance.dsq", "Emote_SuperDance", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/SwingDance.dsq", "Emote_SwingDance", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/ThrowDown.dsq", "Emote_ThrowDown", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/BackFlip.dsq", "Emote_BackFlip", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/ArnoldPosing.dsq", "Emote_ArnoldPosing", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/BellyLaugh.dsq", "Emote_BellyLaugh", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/Bow.dsq", "Emote_Bow", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/Pray.dsq", "Emote_Pray", "0", "8", "1", "0");
   %this.addSequence("art/players/base/Anims/Extra/HangOver.dsq", "Emote_HangOver", "0", "11", "1", "0");
   %this.addSequence("art/players/base/Anims/kneel_right.dsq", "Emote_Kneel_R", "0", "-1", "1", "0");
   %this.addSequence("art/players/base/Anims/kneel_left.dsq", "Emote_Kneel_L", "0", "1", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Angry.dsq", "Emote_Angry", "0", "383", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Bored.dsq", "Emote_Bored", "0", "124", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_BlowKiss.dsq", "Emote_BlowKiss", "0", "84", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Drinking.dsq", "Emote_Drinking", "0", "99", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Eating.dsq", "Emote_Eating", "0", "119", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Salute2.dsq", "Emote_Salute2", "0", "59", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Salute1.dsq", "Emote_Salute1", "0", "59", "1", "0");
   %this.addSequence("art/players/base/Anims/BangShield.dsq", "Emote_BangShield", "0", "24", "1", "0");
   %this.setSequenceCyclic("Emote_BangShield", "1");
   %this.addSequence("art/players/base/Anims/sit_chair.dsq", "Emote_Sit_Chair", "0", "19", "1", "0");
   %this.addSequence("art/players/base/Anims/Sit_ArmChair.dsq", "Emote_Sit_ArmChair", "0", "1", "1", "0");
   %this.addSequence("art/players/base/Anims/Sit_CrossLeg.dsq", "Emote_Sit_CrossLeg", "0", "1", "1", "0");
   %this.addSequence("art/players/base/Anims/Sit_Ground.dsq", "Emote_Sit_Ground", "0", "1", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Stretching.dsq", "Emote_Stretching", "0", "25", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Victory.dsq", "Emote_Victory", "0", "74", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Climbingrope.dsq", "ClimbRope", "0", "29", "1", "0");
   %this.setSequenceCyclic("ClimbRope", "1");
   %this.addSequence("art/players/base/Anims/GA_Climbingwall.dsq", "ClimbWall", "0", "29", "1", "0");
   %this.setSequenceCyclic("ClimbWall", "1");
   %this.addSequence("art/players/base/Anims/GA_Crawling.dsq", "Crawling", "0", "29", "1", "0");
   %this.setSequenceCyclic("Crawling", "1");
   %this.addSequence("art/players/base/Anims/GA_Crouching.dsq", "Crouch", "0", "29", "1", "0");
   %this.setSequenceCyclic("Crouch", "1");
   %this.addSequence("art/players/base/Anims/GA_ClimbingLadderDown.dsq", "LadderDown", "0", "39", "1", "0");
   %this.setSequenceCyclic("LadderDown", "1");
   %this.addSequence("art/players/base/Anims/GA_ClimbingLadderUp.dsq", "LadderUp", "0", "39", "1", "0");
   %this.setSequenceCyclic("LadderUp", "1");
   %this.addSequence("art/players/base/Anims/GA_Digging.dsq", "Digging", "0", "34", "1", "0");
   %this.setSequenceCyclic("Digging", "1");
   %this.addSequence("art/players/base/Anims/GA_LayingDown.dsq", "LayingDown", "0", "60", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_LayingDown.dsq", "LayDown", "0", "69", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Sleeping.dsq", "Sleeping", "0", "74", "1", "0");
   %this.setSequenceCyclic("Sleeping", "1");
   %this.addSequence("art/players/base/Anims/GA_WakingUp.dsq", "WakingUp", "0", "64", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_SittingDown.dsq", "SittingDown", "0", "59", "1", "0");
   %this.addSequence("art/players/base/Anims/GA_Sitting.dsq", "Sitting", "0", "49", "1", "0");
   %this.setSequenceCyclic("Sitting", "1");
   %this.addSequence("art/players/base/Anims/GA_StandingUp.dsq", "StandingUp", "0", "49", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_CombatRoot.dsq", "2HS_CombatRoot", "0", "-1", "1", "0");
   %this.setSequenceCyclic("2HS_CombatRoot", "1");
   %this.addSequence("art/players/base/Anims/2HS_Walk.dsq", "2HS_Walk", "0", "39", "1", "0");
   %this.setSequenceCyclic("2HS_Walk", "1");
   %this.addSequence("art/players/base/Anims/2HS_CombatWalk.dsq", "2HS_CombatWalk", "0", "39", "1", "0");
   %this.setSequenceCyclic("2HS_CombatWalk", "1");
   %this.addSequence("art/players/base/Anims/2HS_Sprint.dsq", "2HS_Sprint", "0", "34", "1", "0");
   %this.setSequenceCyclic("2HS_Sprint", "1");
   %this.addSequence("art/players/base/Anims/2HS_CombatSprint.dsq", "2HS_CombatSprint", "0", "49", "1", "0");
   %this.setSequenceCyclic("2HS_CombatSprint", "1");
   %this.addSequence("art/players/base/Anims/2HS_StrafeLeft.dsq", "2HS_StrafeLeft", "0", "35", "1", "0");
   %this.setSequenceCyclic("2HS_StrafeLeft", "1");
   %this.addSequence("art/players/base/Anims/2HS_StrafeRight.dsq", "2HS_StrafeRight", "0", "34", "1", "0");
   %this.setSequenceCyclic("2HS_StrafeRight", "1");
   %this.addSequence("art/players/base/Anims/2HS_DamageKnockedBack.dsq", "2HS_DamageKnockedBack", "0", "129", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_DamageKnockedFore.dsq", "2HS_DamageKnockedFore", "0", "99", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Damage_Head1.dsq", "2HS_Damage_Head1", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_DuckHighSwing.dsq", "2HS_Duck", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing1.dsq", "2HS_Swing1", "0", "40", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing2.dsq", "2HS_Swing2", "0", "40", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing3.dsq", "2HS_Swing3", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing4.dsq", "2HS_Swing4", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing5.dsq", "2HS_Swing5", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing6.dsq", "2HS_Swing6", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing7.dsq", "2HS_Swing7", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing8.dsq", "2HS_Swing8", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing9.dsq", "2HS_Swing9", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing10.dsq", "2HS_Swing10", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Swing11.dsq", "2HS_Swing11", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Death1.dsq", "2HS_Death1", "0", "132", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Death2.dsq", "2HS_Death2", "0", "139", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Death3.dsq", "2HS_Death3", "0", "139", "1", "0");
   %this.addSequence("art/players/base/Anims/2HS_Death4.dsq", "2HS_Death4", "0", "16", "1", "0");
   %this.addSequence("art/players/base/Anims/H_Root.dsq", "H_Root", "0", "-1", "1", "0");
   %this.setSequenceCyclic("H_Root", "1");
   %this.addSequence("art/players/base/Anims/H_Walk.dsq", "H_Walk", "0", "99", "1", "0");
   %this.setSequenceCyclic("H_Walk", "1");
   %this.addSequence("art/players/base/Anims/H_Gallop.dsq", "H_Gallop", "0", "33", "1", "0");
   %this.setSequenceCyclic("H_Gallop", "1");
   %this.addSequence("art/players/base/Anims/H_Melee1.dsq", "H_Melee1", "0", "44", "1", "0");
   %this.addSequence("art/players/base/Anims/H_Melee2.dsq", "H_Melee2", "0", "44", "1", "0");
   %this.addSequence("art/players/base/Anims/H_Thrown1.dsq", "H_Thrown1", "0", "54", "1", "0");
   %this.addSequence("art/players/base/Anims/H_Damage1.dsq", "H_Damage1", "0", "54", "1", "0");
   %this.addSequence("art/players/base/Anims/H_Death1.dsq", "H_Death1", "0", "44", "1", "0");
   %this.addSequence("art/players/base/Anims/H_WarCry.dsq", "H_WarCry", "0", "49", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_CombatRoot.dsq", "2W_CombatRoot", "0", "49", "1", "0");
   %this.setSequenceCyclic("2W_CombatRoot", "1");
   %this.addSequence("art/players/base/Anims/2W_StrafeLeft.dsq", "2W_StrafeLeft", "0", "34", "1", "0");
   %this.setSequenceCyclic("2W_StrafeLeft", "1");
   %this.addSequence("art/players/base/Anims/2W_StrafeRight.dsq", "2W_StrafeRight", "0", "34", "1", "0");
   %this.setSequenceCyclic("2W_StrafeRight", "1");
   %this.addSequence("art/players/base/Anims/2W_BlockLH1.dsq", "2W_Block_LH1", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_BlockLH2.dsq", "2W_Block_LH2", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_BlockLH3.dsq", "2W_Block_LH3", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_BlockRH1.dsq", "2W_Block_RH1", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_BlockRH2.dsq", "2W_Block_RH2", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_BlockRH3.dsq", "2W_Block_RH3", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing1.dsq", "2W_Swing1", "0", "84", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing3.dsq", "2W_Swing3", "0", "40", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing4.dsq", "2W_Swing4", "0", "154", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing6.dsq", "2W_Swing6", "0", "79", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing8.dsq", "2W_Swing8", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing9.dsq", "2W_Swing9", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing10.dsq", "2W_Swing10", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing11.dsq", "2W_Swing11", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing12.dsq", "2W_Swing12", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing13.dsq", "2W_Swing13", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing14.dsq", "2W_Swing14", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing15.dsq", "2W_Swing15", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing16.dsq", "2W_Swing16", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing17.dsq", "2W_Swing17", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing18.dsq", "2W_Swing18", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing19.dsq", "2W_Swing19", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing20.dsq", "2W_Swing20", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing21.dsq", "2W_Swing21", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing22.dsq", "2W_Swing22", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Damage1.dsq", "2W_Damage1", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_DamageKnockedBack.dsq", "2W_DamageKnockedBack", "0", "131", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Dodge_Duckbelow.dsq", "2W_Dodge_DuckBelow", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Death1.dsq", "2W_Death1", "0", "132", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Death2.dsq", "2W_Death2", "0", "139", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Death4.dsq", "2W_Death4", "0", "16", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Walk.dsq", "2W_Walk", "0", "35", "1", "0");
   %this.setSequenceCyclic("2W_Walk", "1");
   %this.addSequence("art/players/base/Anims/2W_CombatWalk.dsq", "2W_CombatWalk", "0", "39", "1", "0");
   %this.setSequenceCyclic("2W_CombatWalk", "1");
   %this.addSequence("art/players/base/Anims/2W_Sprint.dsq", "2W_Sprint", "0", "25", "1", "0");
   %this.setSequenceCyclic("2W_Sprint", "1");
   %this.addSequence("art/players/base/Anims/2W_CombatSprint.dsq", "2W_CombatSprint", "0", "21", "1", "0");
   %this.setSequenceCyclic("2W_CombatSprint", "1");
   %this.addSequence("art/players/base/Anims/2W_Swing2.dsq", "2W_Swing2", "0", "39", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing5.dsq", "2W_Swing5", "0", "49", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Swing7.dsq", "2W_Swing7", "0", "34", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_DamageKnockedFore.dsq", "2W_DamageKnockedFore", "0", "109", "1", "0");
   %this.addSequence("art/players/base/Anims/2W_Death3.dsq", "2W_Death3", "0", "16", "1", "0");
   %this.setNodeTransform("Root", "0 0 -0.0989928 1 0 0 0", "1");
   %this.setNodeTransform("Left_Cloak", "-0.341676 -0.244328 1.83965 1 0 0 0", "1");
   %this.addNode("mount30", "mount2", "0 0 0 0 0 1 0", "0");
   %this.addNode("mount29", "mount0", "0 0 0 0 0 1 0", "0");
}

$mack = true;
